name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make gcc-arm-linux-gnueabi python2

    - name: Verify DrvGen.py location
      run: ls ${GITHUB_WORKSPACE}/kernel-4.4.95/tools/dct

    - name: Apply dtc build fix
      run: |
        # Patch Makefile.host to avoid multiple definition of 'yylloc'
        sed -i '/dtc-parser.tab.o/d' ${GITHUB_WORKSPACE}/kernel-4.4.95/scripts/Makefile.host

    - name: Build kernel
      run: |
        set -e
        cd kernel-4.4.95
        make O=OUT/5059D/ ARCH=arm CROSS_COMPILE=${GITHUB_WORKSPACE}/tools/arm-linux-androideabi-4.9/bin/arm-linux-androideabi- u5a_plus_o1_defconfig
        sed -i 's/python/python2/' ${GITHUB_WORKSPACE}/kernel-4.4.95/tools/dct/DrvGen.py
        make O=OUT/5059D/ ARCH=arm CROSS_COMPILE=${GITHUB_WORKSPACE}/tools/arm-linux-androideabi-4.9/bin/arm-linux-androideabi- -j6
